from setuptools import setup, find_packages

setup(
    name="thermodynamic_scaling",
    version="0.1.0",
    description="Thermodynamic Scaling Analysis for Language Models",
    author="D. Samuel Hodge",
    author_email="dsamuelhodge@example.com",
    url="https://github.com/DSamuelHodge/thermodynamic-scaling",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "torch>=1.10.0",
        "transformers>=4.18.0",
        "tqdm>=4.62.0",
        "networkx>=2.6.0",
        "jupyter>=1.0.0",
        "ipywidgets>=7.6.0",
    ],
    extras_require={
        "gpu": ["cupy-cuda11x>=10.0.0"],
        "bayesian": ["pymc>=4.0.0", "arviz>=0.12.0"],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
)